# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: ormolu
        name: ormolu
        entry: ormolu --mode inplace
        files: "src/"
        types: [haskell]
        language: system

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
    -   id: markdownlint
